/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package planeta;

/**
 *
 * @author ERNESTO
 */
public class Calculadora extends javax.swing.JFrame {
    double PrimerNumero;
    double SegundoNumero;
    double Resultado;
    String Operador;
    

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        N1 = new javax.swing.JButton();
        N2 = new javax.swing.JButton();
        N3 = new javax.swing.JButton();
        N4 = new javax.swing.JButton();
        N5 = new javax.swing.JButton();
        N6 = new javax.swing.JButton();
        N7 = new javax.swing.JButton();
        N8 = new javax.swing.JButton();
        N9 = new javax.swing.JButton();
        N0 = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnDivi = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(310, 465));
        setMinimumSize(new java.awt.Dimension(310, 465));
        setResizable(false);
        getContentPane().setLayout(null);

        N1.setBackground(new java.awt.Color(153, 153, 255));
        N1.setFont(new java.awt.Font("Segoe Script", 3, 24)); // NOI18N
        N1.setForeground(new java.awt.Color(0, 0, 51));
        N1.setText("1");
        N1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N1ActionPerformed(evt);
            }
        });
        getContentPane().add(N1);
        N1.setBounds(30, 290, 50, 40);

        N2.setBackground(new java.awt.Color(153, 153, 255));
        N2.setFont(new java.awt.Font("Segoe Script", 2, 24)); // NOI18N
        N2.setForeground(new java.awt.Color(0, 0, 51));
        N2.setText("2");
        N2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N2ActionPerformed(evt);
            }
        });
        getContentPane().add(N2);
        N2.setBounds(100, 290, 50, 40);

        N3.setBackground(new java.awt.Color(153, 153, 255));
        N3.setFont(new java.awt.Font("Segoe Script", 2, 24)); // NOI18N
        N3.setForeground(new java.awt.Color(0, 0, 51));
        N3.setText("3");
        N3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N3ActionPerformed(evt);
            }
        });
        getContentPane().add(N3);
        N3.setBounds(170, 290, 50, 40);

        N4.setBackground(new java.awt.Color(153, 153, 255));
        N4.setFont(new java.awt.Font("Segoe Script", 2, 24)); // NOI18N
        N4.setForeground(new java.awt.Color(0, 0, 51));
        N4.setText("4");
        N4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N4ActionPerformed(evt);
            }
        });
        getContentPane().add(N4);
        N4.setBounds(30, 230, 50, 40);

        N5.setBackground(new java.awt.Color(153, 153, 255));
        N5.setFont(new java.awt.Font("Segoe Script", 2, 24)); // NOI18N
        N5.setForeground(new java.awt.Color(0, 0, 51));
        N5.setText("5");
        N5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N5ActionPerformed(evt);
            }
        });
        getContentPane().add(N5);
        N5.setBounds(100, 230, 50, 40);

        N6.setBackground(new java.awt.Color(153, 153, 255));
        N6.setFont(new java.awt.Font("Segoe Script", 2, 24)); // NOI18N
        N6.setText("6");
        N6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N6ActionPerformed(evt);
            }
        });
        getContentPane().add(N6);
        N6.setBounds(170, 230, 50, 40);

        N7.setBackground(new java.awt.Color(153, 153, 255));
        N7.setFont(new java.awt.Font("Segoe Script", 2, 24)); // NOI18N
        N7.setText("7");
        N7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N7ActionPerformed(evt);
            }
        });
        getContentPane().add(N7);
        N7.setBounds(30, 170, 50, 40);

        N8.setBackground(new java.awt.Color(153, 153, 255));
        N8.setFont(new java.awt.Font("Segoe Script", 2, 24)); // NOI18N
        N8.setText("8");
        N8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N8ActionPerformed(evt);
            }
        });
        getContentPane().add(N8);
        N8.setBounds(100, 170, 50, 40);

        N9.setBackground(new java.awt.Color(153, 153, 255));
        N9.setFont(new java.awt.Font("Segoe Script", 2, 24)); // NOI18N
        N9.setText("9");
        N9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N9ActionPerformed(evt);
            }
        });
        getContentPane().add(N9);
        N9.setBounds(170, 170, 50, 40);

        N0.setBackground(new java.awt.Color(153, 153, 255));
        N0.setFont(new java.awt.Font("Segoe Script", 2, 24)); // NOI18N
        N0.setText("0");
        N0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N0ActionPerformed(evt);
            }
        });
        getContentPane().add(N0);
        N0.setBounds(30, 340, 50, 40);

        btnSuma.setBackground(new java.awt.Color(102, 51, 255));
        btnSuma.setFont(new java.awt.Font("Segoe Script", 2, 24)); // NOI18N
        btnSuma.setText("+");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuma);
        btnSuma.setBounds(240, 330, 46, 50);

        btnResta.setBackground(new java.awt.Color(102, 153, 255));
        btnResta.setFont(new java.awt.Font("Segoe Script", 2, 14)); // NOI18N
        btnResta.setText("-");
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });
        getContentPane().add(btnResta);
        btnResta.setBounds(240, 290, 40, 30);

        btnDivi.setBackground(new java.awt.Color(102, 153, 255));
        btnDivi.setFont(new java.awt.Font("Segoe Script", 2, 14)); // NOI18N
        btnDivi.setText("/");
        btnDivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiviActionPerformed(evt);
            }
        });
        getContentPane().add(btnDivi);
        btnDivi.setBounds(240, 210, 40, 30);

        btnMulti.setBackground(new java.awt.Color(102, 153, 255));
        btnMulti.setFont(new java.awt.Font("Segoe Script", 2, 12)); // NOI18N
        btnMulti.setForeground(new java.awt.Color(0, 0, 51));
        btnMulti.setText("X");
        btnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiActionPerformed(evt);
            }
        });
        getContentPane().add(btnMulti);
        btnMulti.setBounds(240, 250, 40, 30);

        btnPunto.setBackground(new java.awt.Color(102, 153, 255));
        btnPunto.setFont(new java.awt.Font("Segoe Script", 2, 24)); // NOI18N
        btnPunto.setForeground(new java.awt.Color(0, 0, 51));
        btnPunto.setText(".");
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPunto);
        btnPunto.setBounds(100, 340, 50, 40);

        btnIgual.setBackground(new java.awt.Color(102, 153, 255));
        btnIgual.setFont(new java.awt.Font("Segoe Script", 2, 24)); // NOI18N
        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });
        getContentPane().add(btnIgual);
        btnIgual.setBounds(170, 340, 50, 40);

        btnLimpiar.setBackground(new java.awt.Color(102, 153, 255));
        btnLimpiar.setFont(new java.awt.Font("Segoe Script", 2, 14)); // NOI18N
        btnLimpiar.setText("C");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(240, 170, 40, 30);

        jTextField1.setBackground(new java.awt.Color(153, 153, 255));
        jTextField1.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 51));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(30, 40, 250, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/planeta/Imagen de WhatsApp 2024-10-24 a las 16.59.48_29eaa1f2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 350, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void N9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N9ActionPerformed
        // TODO add your handling code here:
        String Numero= jTextField1.getText() + N9.getText();
        jTextField1.setText(Numero);
    }//GEN-LAST:event_N9ActionPerformed

    private void N0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N0ActionPerformed
        // TODO add your handling code here:
        String Numero= jTextField1.getText() + N0.getText();
        jTextField1.setText(Numero);
    }//GEN-LAST:event_N0ActionPerformed

    private void btnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiActionPerformed
        // TODO add your handling code here:
        PrimerNumero =Double.parseDouble(jTextField1.getText());
        jTextField1.setText(" ");
        Operador="*";
    }//GEN-LAST:event_btnMultiActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        // TODO add your handling code here:
        PrimerNumero =Double.parseDouble(jTextField1.getText());
        jTextField1.setText(" ");
        Operador="+";
    }//GEN-LAST:event_btnSumaActionPerformed

    private void N1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N1ActionPerformed
        // TODO add your handling code here:
        String Numero= jTextField1.getText() + N1.getText();
        jTextField1.setText(Numero);
    }//GEN-LAST:event_N1ActionPerformed

    private void N2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N2ActionPerformed
        // TODO add your handling code here:
        String Numero= jTextField1.getText() + N2.getText();
        jTextField1.setText(Numero);
    }//GEN-LAST:event_N2ActionPerformed

    private void N3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N3ActionPerformed
        // TODO add your handling code here:
        String Numero= jTextField1.getText() + N3.getText();
        jTextField1.setText(Numero);
    }//GEN-LAST:event_N3ActionPerformed

    private void N4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N4ActionPerformed
        // TODO add your handling code here:
        String Numero= jTextField1.getText() + N4.getText();
        jTextField1.setText(Numero);
    }//GEN-LAST:event_N4ActionPerformed

    private void N5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N5ActionPerformed
        // TODO add your handling code here:
        String Numero= jTextField1.getText() + N5.getText();
        jTextField1.setText(Numero);
    }//GEN-LAST:event_N5ActionPerformed

    private void N6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N6ActionPerformed
        // TODO add your handling code here:
        String Numero= jTextField1.getText() + N6.getText();
        jTextField1.setText(Numero);
    }//GEN-LAST:event_N6ActionPerformed

    private void N7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N7ActionPerformed
        // TODO add your handling code here:
        String Numero= jTextField1.getText() + N7.getText();
        jTextField1.setText(Numero);
    }//GEN-LAST:event_N7ActionPerformed

    private void N8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N8ActionPerformed
        // TODO add your handling code here:
        String Numero= jTextField1.getText() + N8.getText();
        jTextField1.setText(Numero);
    }//GEN-LAST:event_N8ActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        // TODO add your handling code here:
        String Numero= jTextField1.getText() + btnPunto.getText();
        jTextField1.setText(Numero);
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(" ");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        // TODO add your handling code here:
         SegundoNumero =Double.parseDouble(jTextField1.getText());
         if (Operador.equals("+")){
         Resultado=PrimerNumero + SegundoNumero;
         jTextField1.setText(Double.toString(Resultado));
         }else if (Operador.equals("-")){
         Resultado=PrimerNumero - SegundoNumero;
         jTextField1.setText(Double.toString(Resultado));
         }else if (Operador.equals("*")){
         Resultado=PrimerNumero * SegundoNumero;
         jTextField1.setText(Double.toString(Resultado));
         }else if (Operador.equals("/")){
         Resultado=PrimerNumero / SegundoNumero;
         jTextField1.setText(Double.toString(Resultado));
         }
         
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        // TODO add your handling code here:
        PrimerNumero =Double.parseDouble(jTextField1.getText());
        jTextField1.setText(" ");
        Operador="-";
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiviActionPerformed
        // TODO add your handling code here:
        PrimerNumero =Double.parseDouble(jTextField1.getText());
        jTextField1.setText(" ");
        Operador="/";
    }//GEN-LAST:event_btnDiviActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton N0;
    private javax.swing.JButton N1;
    private javax.swing.JButton N2;
    private javax.swing.JButton N3;
    private javax.swing.JButton N4;
    private javax.swing.JButton N5;
    private javax.swing.JButton N6;
    private javax.swing.JButton N7;
    private javax.swing.JButton N8;
    private javax.swing.JButton N9;
    private javax.swing.JButton btnDivi;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
